

IP = "127.0.0.1"
PORT = 1377


PING_REQ = "PNGREQ"
PING_RES = "PNGRES"

LOGIN_REQ = "LGNREQ" # Login request
LOGIN_RES_TRUE = "LGNTRE"
LOGIN_RES_FALSE = "LGNFLS"

REGISTER_REQ = "RGSREQ" # Register request
REGISTER_RES_TRUE = "RGSTRE"
REGISTER_RES_FALSE = "RGSFLS"