
IP = "127.0.0.1"
PORT = 1377


PING_REQ = "PNGREQ"
PING_RES = "PNGRES"

LOGIN_REQ = "LGNREQ" # Login request
LOGIN_RES_TRUE = "LGNTRE"
LOGIN_RES_FALSE = "LGNFLS"

REGISTER_REQ = "RGSREQ" # Register request
REGISTER_RES_TRUE = "RGSTRE"
REGISTER_RES_FALSE = "RGSFLS"

GET_AVAILABLE_ROOMS_REQ = "GAVREQ" # Get available users request
GET_AVAILABLE_ROOMS_RES = "GAVRES" # Get available users response

ADD_ROOM_REQ = "ADRREQ" # Add room request
ADD_ROOM_RES_TRUE = "ADRTRE"
ADD_ROOM_RES_FALSE = "ADRFLS"

JOIN_ROOM_REQ = "JNRREQ" # Join room request
JOIN_ROOM_RES_TRUE = "JNRTRE"
JOIN_ROOM_RES_FALSE = "JNRFLS"

GET_USERS_IN_MY_ROOM_REQ = "GUMREQ" # Get users in my room request
GET_USERS_IN_MY_ROOM_RES = "GUMRES" # Get users in my room response

GET_HOST_USERNAME_REQ = "GHUREQ" # Get host username request
GET_HOST_USERNAME_RES = "GHURES" # Get host username response

SET_GAME_SETTINGS_REQ = "SGSREQ" # Set game settings request
SET_GAME_SETTINGS_RES_TRUE = "SGSTRE"
SET_GAME_SETTINGS_RES_FALSE = "SGSFLS"

GET_GAME_SETTINGS_REQ = "GGSREQ" # Get game settings request
GET_GAME_SETTINGS_RES = "GGSRES" # Get game settings response

START_GAME_REQ = "STGREQ" # Start game request
START_GAME_RES_TRUE = "STGTRE"
START_GAME_RES_FALSE = "STGFLS"

IS_GAME_STARTED_REQ = "IGSREQ" # Is game started request
IS_GAME_STARTED_RES_TRUE = "IGSTRE"
IS_GAME_STARTED_RES_FALSE = "IGSFLS"


GET_GAME_CHANGES = "GGCREQ" # Get game changes request
NUM_OF_CHANGES_EACH_PASS = 100 # Number of changes to send each pass

OPEN_CELL_REQ = "OPCREQ" # Open cell request
OPEN_CELL_RES_TRUE = "OPCTRE"
OPEN_CELL_RES_FALSE = "OPCFLS"